Fixed KWK_ASSERT 'interop' with BOOST_ENABLE_ASSERT_HANDLER.
jfalcou/kiwaku pull request #88
Opened 2023-03-09 10:03 UTC by psiha

Binary/codegen size optimizations.

2023-03-09 12:01 UTC, jfalcou requested changes

2023-03-09 12:01 UTC, jfalcou commented on include/kwk/detail/assert.hpp
> +#include <tuple>
could be cool if we could stick to using kumi::tuple for all tuple things

2023-03-09 12:01 UTC, jfalcou commented on include/kwk/detail/assert.hpp
> +                auto const expanded_tuple{ std::tuple_cat(tuple, std::tuple<StoredArg>{arg}) };
use kumi::cat on kumi::tuple

2023-03-09 12:01 UTC, jfalcou commented on include/kwk/detail/assert.hpp
> +#   ifdef __GNUC__
Can those be in `kiwaku/include/kwk/detail/abi.hpp` or are they very very specific to asserts ?

2023-03-09 12:01 UTC, jfalcou commented on include/kwk/detail/assert.hpp
> +        auto && print_assertion_header(char const * const condition, char const * const file, unsigned const line) noexcept
auto& is enough I guess

2023-03-09 12:01 UTC, jfalcou commented on include/kwk/detail/assert.hpp
> +        std::apply
kumi::apply

2023-03-09 12:01 UTC, jfalcou commented on include/kwk/detail/assert.hpp
> +#endif // KIWAKU_ASSERT
we don't do that :p

2023-03-09 18:25 UTC, psiha commented on include/kwk/detail/assert.hpp
> +#   ifdef __GNUC__
👍

2023-03-09 18:25 UTC, psiha commented on include/kwk/detail/assert.hpp
> +        auto && print_assertion_header(char const * const condition, char const * const file, unsigned const line) noexcept
👍

2023-03-09 18:26 UTC, psiha commented on include/kwk/detail/assert.hpp
> +#endif // KIWAKU_ASSERT
ok :P

2023-03-09 18:35 UTC, jfalcou approved these changes

2023-03-09 18:36 UTC, merged

2023-03-10 07:12 UTC, psiha commented
> should we also change existing call to ASSERT to use , instead of << ?

@jfalcou just saw this question: well that would certainly simplify the cpp implementation portion of the assert macro implementation (i.e. lessen the compile time impact) but that would require more work on your part...